#!/usr/bin/python3
def raise_exception():
    y = "y"
    num = 4
    print(y + num + y)
